[package]
name = "Voxel3d"
version = "0.1.0"
authors = ["CringeKitsune"]
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_flycam = "0.14.1"
rand = "0.8.5"
noise = "0.9.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"

[profile.dev.package."*"]
opt-level = 3
